# Generated by Django 4.2.3 on 2023-07-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('recipient', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
