# Generated by Django 4.2.3 on 2023-07-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='subject',
            new_name='asunto',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='recipient',
            new_name='destinatario',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='message',
            new_name='mensaje',
        ),
    ]
